### ISSUE TITLE
[NUCLEO-32] Any change the STM32F303 will be supported too? 

### ISSUE THREAD

**Issue by rolandvs** [st-sw/I2cReadWriteUtility#1]
Always handy to have such utilities around. However my junk box has the STM32F303 Nucleo board. Any change this will be supported too?

**Comment by st-sw** [comment]
There are so many different STM32 Nucleo boards, it is not possible to support the FW for all existing Hardware.
The I2C application is supported only on some popular boards based on ARM Cortex-M0.

A STM32 Nucleo board only cost $10.  It is an affordable USB-to-I2C solution.
So it is better to just buy a new compatible board.

**Comment by rolandvs** [comment]
Maybe you could consider opening up the application and release the source? And yes I can always use another Nucleo board as part of my collection :-)
